#!/usr/bin/env python3
"""
Send job scan results by email.
Reads new_jobs.json written by job_scanner.py.
Requires GMAIL_APP_PASSWORD environment variable.
"""

import json
import os
import smtplib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

TO_EMAIL = "nicolasmerryyt@gmail.com"
FROM_EMAIL = "nicolasmerryyt@gmail.com"

# Terms that suggest a job slipped through the filter but isn't a fit
MISMATCH_RULES = [
    (["senior", "head of", "director of", "vp ", "vice president", "chief"], "too senior"),
    (["executive producer", "series producer", "supervising producer", "line producer",
      "studio producer", "task producer", "challenge producer"], "too senior / wrong genre"),
    (["sound editor", "audio editor", "audio producer", "dubbing", "foley",
      "dialogue editor", "podcast producer", "radio producer"], "wrong discipline — audio"),
    (["script editor", "script supervisor"], "wrong discipline — script"),
    (["compliance editor", "compliance"], "wrong discipline — compliance/legal"),
    (["casting", "casting director"], "wrong discipline — casting"),
    (["social media manager", "marketing manager", "brand manager"], "wrong discipline — marketing"),
    (["production coordinator", "production manager"], "production management, not editing/directing"),
]


def get_mismatches(title):
    title_lower = title.lower()
    flags = []
    for terms, label in MISMATCH_RULES:
        if any(t in title_lower for t in terms):
            flags.append(label)
    return flags


def build_html(jobs, date_str):
    count = len(jobs)

    job_blocks = ""
    for job in jobs:
        flags = get_mismatches(job["title"])
        flag_html = ""
        if flags:
            flag_html = (
                f'<div style="margin-top:6px;font-size:12px;color:#e08686;">'
                f'⚠ {" · ".join(flags)}</div>'
            )

        title = job["title"]
        # Truncate very long titles (some sites include description text)
        if len(title) > 120:
            title = title[:117] + "…"

        job_blocks += f"""
        <div style="margin-bottom:16px;padding:16px 20px;background:#1a1a1a;
                    border-radius:8px;border:1px solid #2a2a2a;">
            <div style="font-size:15px;font-weight:600;color:#e0e0e0;line-height:1.4;">
                {title}
            </div>
            <div style="font-size:12px;color:#666;margin-top:4px;">
                {job["source"]}
            </div>
            {flag_html}
            <a href="{job["url"]}"
               style="display:inline-block;margin-top:10px;font-size:13px;
                      color:#86E0A8;text-decoration:none;">
                View listing →
            </a>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#0f0f0f;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:620px;margin:0 auto;padding:32px 24px;">

    <div style="border-bottom:1px solid #2a2a2a;padding-bottom:20px;margin-bottom:28px;">
      <div style="font-size:22px;font-weight:700;color:#86E0A8;letter-spacing:-0.3px;">
        Job Scan
      </div>
      <div style="font-size:13px;color:#555;margin-top:6px;">
        {date_str} &nbsp;·&nbsp; {count} new job{"s" if count != 1 else ""}
      </div>
    </div>

    {job_blocks}

    <div style="margin-top:32px;font-size:11px;color:#333;text-align:center;">
      Generated by job_scanner.py · GitHub Actions
    </div>
  </div>
</body>
</html>"""
    return html


def build_plain(jobs, date_str):
    lines = [f"Job Scan — {date_str} · {len(jobs)} new job(s)\n"]
    for job in jobs:
        flags = get_mismatches(job["title"])
        title = job["title"][:120] + ("…" if len(job["title"]) > 120 else "")
        lines.append(f"• {title}")
        lines.append(f"  Source: {job['source']}")
        if flags:
            lines.append(f"  ⚠ {' · '.join(flags)}")
        lines.append(f"  {job['url']}")
        lines.append("")
    return "\n".join(lines)


def main():
    try:
        with open("new_jobs.json", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        print("new_jobs.json not found — nothing to send.")
        sys.exit(0)

    jobs = data.get("jobs", [])
    date_str = data.get("date", "")

    if not jobs:
        print("No new jobs this scan — skipping email.")
        sys.exit(0)

    password = os.environ.get("GMAIL_APP_PASSWORD")
    if not password:
        print("GMAIL_APP_PASSWORD not set — cannot send email.")
        sys.exit(1)

    subject = f"Job Scan — {len(jobs)} new job{'s' if len(jobs) != 1 else ''} · {date_str}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = FROM_EMAIL
    msg["To"] = TO_EMAIL
    msg.attach(MIMEText(build_plain(jobs, date_str), "plain"))
    msg.attach(MIMEText(build_html(jobs, date_str), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(FROM_EMAIL, password)
        smtp.send_message(msg)

    print(f"Email sent: {len(jobs)} new jobs to {TO_EMAIL}")


if __name__ == "__main__":
    main()
